### **3.2 Baseline Model**

In this practical, you'll build your first baseline models for time series forecasting. A baseline model is a simple, intuitive approach to prediction - often based on straightforward rules or heuristics - and acts as a reference point for evaluating more complex models later on.

Using quarterly earnings data from Johnson & Johnson, you will explore how features like trend and seasonality affect forecasts and learn to construct several naive forecasting models.

The dataset for this practical is the `JohnsonAndJohnson.csv` file.

This activity has been adapted from [this book](https://www.manning.com/books/time-series-forecasting-in-python-book)

**Step 1: Import Libraries and Read the Data**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime

In [3]:
df = pd.read_csv('./data/JohnsonAndJohnson_4.csv')
df.head()

        time  JohnsonJohnson
0   1/1/1960            0.71
1   1/4/1960            0.63
2   2/7/1960            0.85
3  1/10/1960            0.44
4   1/1/1961            0.61

**Step 2: Check if the time attribute is DateTime, otherwise convert to DateTime datatype**

We will do the following:

- check the data type

- convert to datatime data type (if needed)

- check the head() and tail() to inspect the data values

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   time            84 non-null     str
 1   JohnsonJohnson  84 non-null     float64
dtypes: float64(1), str(1)
memory usage: 1.4 KB

In [5]:
df["time"] = pd.to_datetime(df["time"], dayfirst=True)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   time            84 non-null     datetime64[us]
 1   JohnsonJohnson  84 non-null     float64
dtypes: datetime64[us](1), float64(1)
memory usage: 1.4 KB

In [6]:
df.head()

        time  JohnsonJohnson
0 1960-01-01            0.71
1 1960-04-01            0.63
2 1960-07-02            0.85
3 1960-10-01            0.44
4 1961-01-01            0.61

In [7]:
df.tail()

         time  JohnsonJohnson
79 1979-10-01            9.99
80 1980-01-01           16.20
81 1980-04-01           14.67
82 1980-07-02           16.02
83 1980-10-01           11.61

Our data time is now `Year-Month-Day`

**Step 3: Let's look at the data**

We will plot the data.